In [8]:

import numpy as np

import pandas as pd

employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Karan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"]
})

print(employees)

   Emp_ID   Name Department
0     101  Rahul         IT
1     102   Aman         HR
2     103  Priya         IT
3     104   Neha    Finance
4     105  Karan         HR

In [9]:
salary = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 106, 107],
    "Salary": [45000, 55000, 60000, 70000, 50000]
})

print(salary)

   Emp_ID  Salary
0     101   45000
1     102   55000
2     103   60000
3     106   70000
4     107   50000

In [10]:
pd.merge(employees,salary)

   Emp_ID   Name Department  Salary
0     101  Rahul         IT   45000
1     102   Aman         HR   55000
2     103  Priya         IT   60000

In [11]:
pd.merge(employees,salary,on="Emp_ID",how="inner" )

   Emp_ID   Name Department  Salary
0     101  Rahul         IT   45000
1     102   Aman         HR   55000
2     103  Priya         IT   60000

In [12]:
pd.merge(employees,salary,on="Emp_ID",how="outer" )

   Emp_ID   Name Department   Salary
0     101  Rahul         IT  45000.0
1     102   Aman         HR  55000.0
2     103  Priya         IT  60000.0
3     104   Neha    Finance      NaN
4     105  Karan         HR      NaN
5     106    NaN        NaN  70000.0
6     107    NaN        NaN  50000.0

In [13]:
pd.merge(employees,salary,on="Emp_ID",how="left" )

   Emp_ID   Name Department   Salary
0     101  Rahul         IT  45000.0
1     102   Aman         HR  55000.0
2     103  Priya         IT  60000.0
3     104   Neha    Finance      NaN
4     105  Karan         HR      NaN

In [15]:
pd.merge(employees,salary,on="Emp_ID",how= "right")

   Emp_ID   Name Department  Salary
0     101  Rahul         IT   45000
1     102   Aman         HR   55000
2     103  Priya         IT   60000
3     106    NaN        NaN   70000
4     107    NaN        NaN   50000

In [16]:
import pandas as pd

df1 = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Name": ["Rahul", "Aman", "Priya"],
    "Department": ["IT", "HR", "Finance"]
})

print(df1)

   Emp_ID   Name Department
0     101  Rahul         IT
1     102   Aman         HR
2     103  Priya    Finance

In [17]:
df2 = pd.DataFrame({
    "Emp_ID": [104, 105, 106],
    "Name": ["Neha", "Karan", "Ravi"],
    "Department": ["IT", "HR", "Finance"]
})

print(df2)

   Emp_ID   Name Department
0     104   Neha         IT
1     105  Karan         HR
2     106   Ravi    Finance

In [19]:
result = pd.concat([df1, df2])

print(result)

   Emp_ID   Name Department
0     101  Rahul         IT
1     102   Aman         HR
2     103  Priya    Finance
0     104   Neha         IT
1     105  Karan         HR
2     106   Ravi    Finance

In [20]:
result = pd.concat([df1, df2],axis=1)

print(result)

   Emp_ID   Name Department  Emp_ID   Name Department
0     101  Rahul         IT     104   Neha         IT
1     102   Aman         HR     105  Karan         HR
2     103  Priya    Finance     106   Ravi    Finance

In [21]:
import pandas as pd

employees = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT"]
}, index=[101, 102, 103, 104])

print(employees)

      Name Department
101  Rahul         IT
102   Aman         HR
103  Priya    Finance
104   Neha         IT

In [22]:
salary = pd.DataFrame({
    "Salary": [45000, 55000, 60000, 70000],
    "Bonus": [5000, 6000, 7000, 8000]
}, index=[101, 102, 103, 105])

print(salary)

     Salary  Bonus
101   45000   5000
102   55000   6000
103   60000   7000
105   70000   8000

In [23]:
result = employees.join(salary)

print(result)

      Name Department   Salary   Bonus
101  Rahul         IT  45000.0  5000.0
102   Aman         HR  55000.0  6000.0
103  Priya    Finance  60000.0  7000.0
104   Neha         IT      NaN     NaN