In [22]:
import numpy as np
import pandas as pd

In [34]:
data ={
    'A':[1,2,1,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df =pd.DataFrame(data)

In [35]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  1  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [36]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [37]:
df.isna().sum()

A    0
B    0
C    2
D    3
dtype: int64

In [38]:
 df.isna().any()

A    False
B    False
C     True
D     True
dtype: bool

In [39]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  1  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [40]:
df.dropna(thresh =3)

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  1  3  3.0  NaN
4  5  5  NaN  5.0

Filling Values

In [41]:
values ={'A':0,'B':100,"C":300,"D":300}

In [42]:
df.fillna(value=values)

   A  B      C      D
0  1  1    1.0    1.0
1  2  2    2.0  300.0
2  1  3    3.0  300.0
3  4  4  300.0  300.0
4  5  5  300.0    5.0