In [1]:
import numpy as numpy
import pandas as pd

In [2]:
data = {"Name":['john','anna','peter','linda'],
       'age' :[20,56,85,60],
       'City':['Newyork','paris','berlin','londonn'],
       'Salary':[65000,45000,12022,55555]}
df = pd.DataFrame(data)

In [3]:
df

    Name  age     City  Salary
0   john   20  Newyork   65000
1   anna   56    paris   45000
2  peter   85   berlin   12022
3  linda   60  londonn   55555

In [45]:
data_list = [['john',20,'newyork',65000],
        ["Anna",56,"Paris",45000],
        ["peter",80,'berlin',100000],
       ["Linda",60,"Paris",55555]]
df2 = pd.DataFrame(data_list)
coloumns =["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=coloumns)

In [46]:
df2

    Name  Age     City  Salary
0   john   20  newyork   65000
1   Anna   56    Paris   45000
2  peter   80   berlin  100000
3  Linda   60    Paris   55555

In [47]:
 df2["Name"]

0     john
1     Anna
2    peter
3    Linda
Name: Name, dtype: object

In [48]:
 df2[["Name","Age"]]

    Name  Age
0   john   20
1   Anna   56
2  peter   80
3  Linda   60

creating a new column

In [49]:
df2["Designation"] =["Doctor","eng","Doc","eng"]

In [50]:
df2

    Name  Age     City  Salary Designation
0   john   20  newyork   65000      Doctor
1   Anna   56    Paris   45000         eng
2  peter   80   berlin  100000         Doc
3  Linda   60    Paris   55555         eng

Removing Column

In [51]:
df2.drop("Designation",axis=1)

    Name  Age     City  Salary
0   john   20  newyork   65000
1   Anna   56    Paris   45000
2  peter   80   berlin  100000
3  Linda   60    Paris   55555

In [52]:
df2.drop("Designation",axis=1,inplace= True)

In [53]:
df2

    Name  Age     City  Salary
0   john   20  newyork   65000
1   Anna   56    Paris   45000
2  peter   80   berlin  100000
3  Linda   60    Paris   55555

In [54]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   56   Paris   45000
2  peter   80  berlin  100000
3  Linda   60   Paris   55555

Selecting Rows

In [55]:
df2.loc[[0,1]]

   Name  Age     City  Salary
0  john   20  newyork   65000
1  Anna   56    Paris   45000

In [56]:
df2.iloc[3]

Name      Linda
Age          60
City      Paris
Salary    55555
Name: 3, dtype: object

Selecting particular portion

In [57]:
df2.loc[[0,1]][["City","Salary"]]

      City  Salary
0  newyork   65000
1    Paris   45000

In [58]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  peter   80
3  Linda   60

 Condtional Selection

In [59]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   56   Paris   45000
2  peter   80  berlin  100000
3  Linda   60   Paris   55555

TypeError: unhashable type: 'Series'